# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'task1.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMainWindow, QApplication, QLabel, QRadioButton
from PyQt5.QtGui import QPixmap
from PyQt5.QtCore import Qt
import requests
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(685, 443)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 20, 400, 400))
        self.label.setText("")
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(560, 50, 91, 21))
        self.lineEdit.setObjectName("lineEdit")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(520, 50, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(520, 90, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(560, 90, 91, 21))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(560, 130, 91, 21))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(520, 130, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(520, 170, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.radiobutton = QRadioButton(self.centralwidget)
        self.radiobutton.setChecked(True)
        self.radiobutton.setFont(font)

        self.radiobutton_2 = QRadioButton(self.centralwidget)
        self.radiobutton_2.setChecked(True)
        self.radiobutton_2.setFont(font)
        self.radiobutton_2.setGeometry(QtCore.QRect(90, 5, 140, 15))

        self.radiobutton_3 = QRadioButton(self.centralwidget)
        self.radiobutton_3.setChecked(True)
        self.radiobutton_3.setFont(font)
        self.radiobutton_3.setGeometry(QtCore.QRect(160, 5, 210, 16))

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 685, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "lon"))
        self.label_3.setText(_translate("MainWindow", "lat"))
        self.label_4.setText(_translate("MainWindow", "spn"))
        self.pushButton.setText(_translate("MainWindow", "Загрузить"))
        self.radiobutton.setText(_translate("MainWindow", "Спутник"))
        self.radiobutton_2.setText(_translate("MainWindow", "Схема"))
        self.radiobutton_3.setText(_translate("MainWindow", "Гибрид"))


class MyWidget(QMainWindow, Ui_MainWindow):
    def __init__(self):
        super().__init__()
        self.setupUi(self)
        self.pushButton.clicked.connect(self.button)
        self.radiobutton.clicked.connect(self.onClicked)
        self.radiobutton_2.clicked.connect(self.onClicked)
        self.radiobutton_3.clicked.connect(self.onClicked)
        self.map_type = "map"
        # 37.530887 55.703118 0.002

    def button(self):
        self.lon, self.lat, self.delta = self.lineEdit.text(), self.lineEdit_2.text(), self.lineEdit_3.text()

        self.getImage(self.lon, self.lat, self.delta, self.map_type)
        self.setImage()

    def getImage(self, lon, lat, delta, map_type):
        api_server = "http://static-maps.yandex.ru/1.x/"
        params = {
            "ll": ",".join([lon, lat]),
            "spn": ",".join([delta, delta]),
            "l": map_type
        }

        map_request = api_server + params['ll'] + params['spn'] + params['l']
        response = requests.get(api_server, params=params)

        if not response:
            print("Ошибка выполнения запроса:")
            print(map_request)
            print("Http статус:", response.status_code, "(", response.reason, ")")
            sys.exit(1)

        self.map_file = "map.png"
        with open(self.map_file, "wb") as file:
            file.write(response.content)

    def setImage(self):
        self.pixmap = QPixmap(self.map_file)
        self.label.setPixmap(self.pixmap)

    def keyPressEvent(self, event):
        try:
            if event.key() == Qt.Key_PageUp:
                self.delta = float(self.delta)
                self.delta = str(float(self.delta) / 2)
                self.getImage(self.lon, self.lat, self.delta, self.map_type)
                self.setImage()

            if event.key() == Qt.Key_PageDown:
                self.delta = float(self.delta)
                if self.delta < 16:
                    self.delta = str(self.delta * 2)
                    self.getImage(self.lon, self.lat, self.delta, self.map_type)
                    self.setImage()

            elif event.key() == Qt.Key_W:
                self.lat = float(self.lat)
                self.lat += 0.4
                self.lat = str(self.lat)

                self.getImage(self.lon, self.lat, self.delta, self.map_type)
                self.setImage()

            elif event.key() == Qt.Key_S:
                self.lat = float(self.lat)
                self.lat -= 0.4
                self.lat = str(self.lat)

                self.getImage(self.lon, self.lat, self.delta, self.map_type)
                self.setImage()

            elif event.key() == Qt.Key_A:
                self.lon = float(self.lon)
                self.lon -= 0.4
                self.lon = str(self.lon)

                self.getImage(self.lon, self.lat, self.delta, self.map_type)
                self.setImage()

            elif event.key() == Qt.Key_D:
                self.lon = float(self.lon)
                self.lon += 0.4
                self.lon = str(self.lon)

                self.getImage(self.lon, self.lat, self.delta, self.map_type)
                self.setImage()
        except Exception as e:
            pass

    def onClicked(self):
        if self.radiobutton.isChecked():
            self.map_type = "sat"
        elif self.radiobutton_2.isChecked():
            self.map_type = "map"
        else:
            self.map_type = "sat,skl"


if __name__ == '__main__':
    app = QApplication(sys.argv)
    ex = MyWidget()
    ex.show()
    sys.exit(app.exec_())
